### ISSUE TITLE
[BUG 🪲] Python version returns error when trying to start a WindowsCapture

### ISSUE THREAD

**Issue by Luis-Munu** [NiiightmareXD/windows-capture#23]
**Describe the bug 🐛**
After freshly installing the library using the pip command, trying to run the example code of the Python version of the library returns the following error:
`Exception: Capture Session Threw An Exception -> Failed To Initialize WinRT`

On line: `capture.start()`

I didn't had rust installed in the system but it did not work even after installing it (if that was even a requirement, which I don't know)

**Expected behavior 📝**
The script should start storing frames as the screen's content changes.
 
**OS 🤖**
 - Version: Windows 11
 - Build 22H2 Insider Pro

**Comment by Luis-Munu** [comment]
Apparently it was solved by restarting, weird stuff

**Comment by skibidi-sigma12351** [comment]
hey im getting ur error and tried restarting but still getting it

**Comment by NiiightmareXD** [comment]
> hey im getting ur error and tried restarting but still getting it

What is you windows version?

**Comment by skibidi-sigma12351** [comment]
> > hey im getting ur error and tried restarting but still getting it
> 
> What is you windows version?

my window is 10 version: 22H2
Os build: 19045.4651
